name: BeeConomy
main: com.shanebeestudios.bc.BeeConomy
version: '${project.version}'
author: ShaneBee
api-version: "1.13"
softdepend:
  - Vault
commands:
  eco:
    description: Base economy command
    aliases:
      - economy
      - money
