name: BeeConomy
main: com.shanebeestudios.bc.BeeConomy
version: '${project.version}'
author: ShaneBee
description: A simple and easy to use economy system.
website: https://github.com/ShaneBeeStudios/BeeConomy
api-version: "1.13"
softdepend:
  - Vault
commands:
  eco:
    description: Base economy command
    aliases:
      - economy
      - money
